apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-13T19:46:51Z"
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  resourceVersion: "517"
  uid: e8f1b4e5-5741-40bd-898b-fb960bdc36c1
spec:
  clusterIP: 10.108.171.226
  clusterIPs:
  - 10.108.171.226
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31880
    port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.servicePort }}
  selector:
    app: {{ .Values.appName }}
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
